---
name: Dieng
surname: Samba
position: "Elève ingénieur statisticien économiste"
address: "Niarry Tally, Dakar, Sénégal"
phone: 781607238
pronouns: her
email: "sambadiengys122003@gmail.com"

github: sambadieng122003
linkedin: Samba Dieng
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Je suis un sénégalais passionné de la programmation et de la statistique. J'aimerai travailler dans la data science. Par ailleurs je suis très intéressé par l'économie, la psychologie"
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```



# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Baccalauréat", "2021-2022", "Lycée Thierno Saidou Nourou Tall", "Poit E, Dakar",
  "Eleve ingénieur statisticien économiste en 2e année", "2023-2024", "ENSAE Pierre Ndiaye", "Dakar, Sénégal",
  
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Compétences
*Word+PowerPoint*,*SPSS*,*STATA*,*EXCEL+VBA*,*PYTHON*,
*QGIS*,*R*,*C/C++*
 
# Langue
Francais: Niveau avancé
